# Generated by Django 2.0.2 on 2018-03-02 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20180302_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='info_url',
            field=models.URLField(max_length=1024, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(default='', max_length=1024, unique=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
    ]
