# Generated by Django 2.0.2 on 2018-03-02 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20180302_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address_2',
            field=models.CharField(blank='true', default='', max_length=255),
        ),
    ]
