# Generated by Django 2.0.2 on 2018-04-02 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_auto_20180329_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
