# Generated by Django 2.0.2 on 2018-04-15 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_auto_20180415_0118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='url',
            new_name='linkedin_url',
        ),
        migrations.AddField(
            model_name='company',
            name='employees_on_linkedin',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.CharField(default='', max_length=1024, unique=True),
        ),
    ]
