# Generated by Django 2.0.2 on 2018-03-04 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='tradeshow_booth',
            field=models.CharField(default='', max_length=255),
        ),
    ]
