# Generated by Django 2.0.2 on 2018-03-04 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20180304_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='info_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
