# Generated by Django 2.0.2 on 2018-03-29 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_auto_20180313_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.CharField(blank=True, default='', max_length=255, unique=True),
        ),
    ]
