# Generated by Django 2.0.2 on 2018-04-15 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_auto_20180402_0132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='city',
            new_name='companyId',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='country',
            new_name='company_headcount',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='tradeshow_booth',
            new_name='geography',
        ),
        migrations.RemoveField(
            model_name='company',
            name='address',
        ),
        migrations.RemoveField(
            model_name='company',
            name='address_2',
        ),
        migrations.RemoveField(
            model_name='company',
            name='description',
        ),
        migrations.RemoveField(
            model_name='company',
            name='employees',
        ),
        migrations.RemoveField(
            model_name='company',
            name='info_url',
        ),
        migrations.RemoveField(
            model_name='company',
            name='lead_source',
        ),
        migrations.RemoveField(
            model_name='company',
            name='website',
        ),
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='url',
            field=models.CharField(default='', max_length=1024, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
