# Generated by Django 2.0.2 on 2018-04-15 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_auto_20180415_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, unique=True),
        ),
    ]
