# Generated by Django 2.0.2 on 2018-06-15 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0012_auto_20180415_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='employee_email',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='employee_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='employee_position',
            field=models.CharField(default='', max_length=255),
        ),
    ]
